### ISSUE TITLE
Any chance for the v2.public interface?

### ISSUE THREAD

**Issue by Indigo744** [authenticvision/libpaseto#1]
Hello,

Thanks for this implementation. Do you think the `v2.public` interface will be supported by this lib one day?

Thanks.

**Comment by minus7** [comment]
Sorry for the late reply; I didn't have notifications enabled for this repo somehow.

I do plan to add v2.public (even started a bit already), though it's not high up on the priority list.

**Comment by minus7** [comment]
Just pushed v2.public and also tagged it as release candidate for 1.0
