### ISSUE TITLE
Will paseto_v2_encrypt always terminate with a nul \0 byte?

### ISSUE THREAD

**Issue by jackturnbull** [authenticvision/libpaseto#2]
Apologies for the incorrect use of an issue but it feels like the best place to ask. I need a little guidance since I'm not very proficient at reading C and don't want to take something for granted that could potentially be unsafe.

I've written some [Crystal](https://crystal-lang.org/) C bindings for this library and the largest area of concern is that I'm allowing the Crystal [string initialiser](https://crystal-lang.org/api/0.26.1/String.html#new%28chars%3APointer%28UInt8%29%29-class-method) to step over the returned pointer from `paseto_v2_encrypt` which appears to terminate whenever reaches a zero byte.

The [libsodium docs](https://download.libsodium.org/doc/helpers/#base64-encoding-decoding) suggest that the returned char* will be terminated with a `\0` character so I'm assuming that would be enough in this instance?

Thanks for the lib!

**Comment by minus7** [comment]
Hi,
The string returned from `paseto_v2_encrypt` is standard C string and thus is null-terminated. The [docs in the header file](https://github.com/authenticvision/libpaseto/blob/c7aaccfebafdc6605e4660ed9d32218cf7573f7b/include/paseto.h#L34) also mention this.

Nice that you're building Crystal bindings for paseto :+1:

**Comment by jackturnbull** [comment]
Ah that's a little embarassing - totally missed that. Thanks :smile:

**Comment by minus7** [comment]
FYI I just changed the API and added v2.public. You might want to update :)

**Comment by jackturnbull** [comment]
Oh wow good update! I'll get onto that this weekend, thanks :)
